### PR TITLE
inverter class changes

### LINKED ISSUE #16: write-safe register list
https://github.com/hoggyhoggy/givenergy-modbus-async/blob/85675ba2a0c03a4a6dd0f7f81d1d3cd65db2716b/givenergy_modbus/pdu/write_registers.py#L20
https://github.com/hoggyhoggy/givenergy-modbus-async/blob/85675ba2a0c03a4a6dd0f7f81d1d3cd65db2716b/givenergy_modbus/client/commands.py#L23

It's not ideal that there are separate list of registers scattered about the tree. Would be good to align it with the register definitions in inverter.py  (Presuambly to a first approximation, if it's named in the inverter list of registers, it's safe to write to ?  

Might possibly special-case reboot - it's not _very_ safe to write to, since arbitrary values can cause problems ?

### LINKED ISSUE #20: defaulting missing / unfetched registers to 0
https://github.com/hoggyhoggy/givenergy-modbus-async/blob/30a1b1d8a43ef2578cd7305b96366804174e3811/givenergy_modbus/model/register_cache.py#L17

Took me a little while to understand this... the cache is a DefaultDict which means that creates entries on the fly rather than raising a key exception. I guess I don't feel strongly about that either way.

However, it's defaulting to 0, which is a perfectly valid register value. That seems wrong, since it means we can't distingush between an actual value of 0, and a not-yet-retrieved value.   Or if you've got an older inverter and ask for one of the higher register names that doesn't exist, you get 0, which you could very easily misinterpret.

I wonder if defaulting to None would be better.  All the converters in register.py seem to guard for None values, so the None value should propagate back to the caller. Would need yet more testing, of course...

-1 is another option, since raw register reads would always get 0 to 65535. But None seems safer.

### PR DESCRIPTION
**Pull request by divenal**
Next round of structural changes, for review/comment.
closes https://github.com/hoggyhoggy/givenergy-modbus-async/issues/20
closes https://github.com/hoggyhoggy/givenergy-modbus-async/issues/16

### CODE REVIEW

**Comment by divenal** [comment]
Sorry about that - having another go
These are again relative to the prepare-for-1.0 branch rather than the dev branches.

Main changes are getting rid of pydantic for inverter and battery classes, so that the classes now convert values on the fly when individual attributes are accessed, rather than converting everything to friendly format in python attributes when the inverter object itself is instantiated.

And then subsequent to that, introduce an optional 'valid' field to the master copy of the holding register definitions in inverter.py. Provide a mechanism to remove the register list in commands.py but I haven't actually gone ahead and converted the existing commands yet.

(Just realised that the one timeslot register I had aliased - charge_slot_2 - was actually defined incorrectly in inverter.py !)

**Comment by divenal** [comment]
Being profoundly lazy, I didn't relish the prospect of manually entering dozens of trivial setter methods in commands.py
Nor maintaining such a suite. Fortunately, I think it can be done on the fly...   (We'd still keep the non-trivial ones as explicit methods.)

In a similar way to how (with this change),  access to inverter.xyz results in a call to inverter.get('xyz'), I'm pretty sure I can set things up so that  Commands.set_xyz(value) turns into a call to Commands.write_named_register('xyz', value)

And I can probably special-case  set_xxx_slot_y()  and assume it's a timeslot, and so (try to) write to  'xxx_slot_y_start' and 'xxx_slot_y_end'.

**Comment by divenal** [comment]
(Just noticed that I had managed to break the conversion of the system time to a datetime. Updated now.)

**Comment by divenal** [comment]
Any progress on reviewing or merging these ?  I have more changes in the pipeline - I could add them to this branch, which (I'm guessing) they would get included in any pull request, or I could hang on for now.

Merging changes is relatively benign in git - if you decide you don't like a change, you can create a retrospective branch before it and resume development as if it was never incorporated.

**Comment by hoggyhoggy** [comment]
Sorry, Been incredibly hectic at work so had no free time lately. Let me have a quick look through but suspect i'll just do a merge and all will be fine. 
(Same goes for why I've been quiet elsewhere on here)

**Pull request merged**
